- .github/CODEOWNERS
- .github/dependbot.yml
- .github/pull_request_template.md
- Adds initial git code to the repo
[CRM457-357](https://dsdmoj.atlassian.net/browse/CRM457-357)
[CRM457-357]: https://dsdmoj.atlassian.net/browse/CRM457-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-357 - Add initial git code

- .circleci/config.yml
- Pipfile.lock
Adds initial config for CircleCI to do linting, tests and docker image scanning
[CRM457-357](https://dsdmoj.atlassian.net/browse/CRM457-357)
[CRM457-357]: https://dsdmoj.atlassian.net/browse/CRM457-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-357 - Add initial circleci config

- .circleci/config.yml
- helm_deploy/laa-crime-application-store/.helmignore
- helm_deploy/laa-crime-application-store/Chart.yaml
- helm_deploy/laa-crime-application-store/templates/NOTES.txt
- helm_deploy/laa-crime-application-store/templates/_helpers.tpl
- helm_deploy/laa-crime-application-store/templates/deployment.yaml
- helm_deploy/laa-crime-application-store/templates/ingress.yaml
- helm_deploy/laa-crime-application-store/templates/service.yaml
- helm_deploy/laa-crime-application-store/templates/tests/test-connection.yaml
- helm_deploy/laa-crime-application-store/values-development.yaml
- helm_deploy/laa-crime-application-store/values-production.yaml
- helm_deploy/laa-crime-application-store/values-uat.yaml
- helm_deploy/laa-crime-application-store/values.yaml
- Adds Helm Deployment script
- Updates build config to deploy to this env
[CRM457-372](https://dsdmoj.atlassian.net/browse/CRM457-372)
[CRM457-372]: https://dsdmoj.atlassian.net/browse/CRM457-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-372 - Add initial helm config

- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- laa_crime_application_store_app/config/logging_config.py
- laa_crime_application_store_app/main.py
- Adds structlog and initial config into application
[CRM457-373](https://dsdmoj.atlassian.net/browse/CRM457-373)
[CRM457-373]: https://dsdmoj.atlassian.net/browse/CRM457-373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CTSKF-373 - Add structlog to app

- .coveragerc
- Pipfile
- Pipfile.lock
- helm_deploy/laa-crime-application-store/templates/deployment.yaml
- laa_crime_application_store_app/config/app_settings.py
- laa_crime_application_store_app/main.py
Adds sentry to the application
[CRM457-361](https://dsdmoj.atlassian.net/browse/CRM457-361)
Secret has been setup in env and sentry project is available
[CRM457-361]: https://dsdmoj.atlassian.net/browse/CRM457-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM456-361 - Add Sentry to application

- .circleci/config.yml
- alembic.ini
- alembic/README.md
- alembic/env.py
- alembic/generate_db.py
- laa_crime_application_store_app/data/database.py
- laa_crime_application_store_app/main.py
- laa_crime_application_store_app/models/application.py
- laa_crime_application_store_app/routers/application.py
- laa_crime_application_store_app/schema/application_schema.py
- tests/data/database_test.py
- tests/routers/application_test.py
- tests/routers/conftest.py
> Initial ORM implementation

- Pipfile
- Pipfile.lock
Adds typing-extensions as this was causing an error on deployment because it was missing. 
N/A
> Add missing dependency

- Dockerfile
Adds alembic folder and config to docker for migrations
N/A
> Add Alembic folder/config

- .env.sample
- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- laa_crime_application_store_app/config/external_server_settings.py
- laa_crime_application_store_app/internal/notifier.py
- laa_crime_application_store_app/models/application_metadata.py
- laa_crime_application_store_app/models/application_post_request.py
- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/application_schema.py
- pytest.ini
- tests/internal/conftest.py
- tests/internal/notifier_test.py
- tests/routers/conftest.py
- tests/routers/v1/application_test.py
Basic structure to send metadata to case worker app
This is not currently hooked in or tested and is in place to allow conversation regarding approach and case worker app implementation (also WIP)
[CRM457-405](https://dsdmoj.atlassian.net/browse/CRM457-)
[CRM457-405]: https://dsdmoj.atlassian.net/browse/CRM457-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 405/message case worker app

- .gitignore
- alembic/versions/3a99fcfd6934_add_form_type.py
- alembic/versions/4728f5eac46d_add_events_to_claim.py
- laa_crime_application_store_app/models/application.py
- laa_crime_application_store_app/models/application_new.py
- laa_crime_application_store_app/models/application_update.py
- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/application_schema.py
- tests/routers/conftest.py
- tests/routers/v1/application_test.py
- Adds application_type to the DB and updates existing rows to be crm7
- Adds application_type to models to allow it to come through in requests
- Updates tests
N/A
> Add application type to store

- .circleci/config.yml
Adds deployment to UAT environment
N/A
> Add UAT deployment

- helm_deploy/laa-crime-application-store/values-production.yaml
- Fix namespace in helm values
> Update prod namespace

- alembic/generate_db.py
- alembic/versions/325c09fdc880_add_updated_at_to_application.py
- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/application_schema.py
- tests/routers/conftest.py
- tests/routers/v1/application_test.py
Add updated_at field on application to support polling from CW and Provider applications
[CRM457-681](https://dsdmoj.atlassian.net/browse/CRM457-681)
[CRM457-681]: https://dsdmoj.atlassian.net/browse/CRM457-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 681/updated at

- laa_crime_application_store_app/models/basic_application.py
- laa_crime_application_store_app/routers/v1/application.py
- tests/routers/v1/application_test.py
Add /applications endpoint returning basic application information
[CRM457-693](https://dsdmoj.atlassian.net/browse/CRM457-693)
[CRM457-693]: https://dsdmoj.atlassian.net/browse/CRM457-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add applications endpoint

- laa_crime_application_store_app/config/database_settings.py
- laa_crime_application_store_app/data/database.py
- laa_crime_application_store_app/main.py
- laa_crime_application_store_app/routers/index.py
- laa_crime_application_store_app/routers/v1/application.py
- Move router version prefix to main.py
- Move index router to own file
- Add database config to its own file and do not use os.environment
- Update usage in code
> Minor application Cleanup

- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/basic_application.py
- laa_crime_application_store_app/schema/secure_json_response.py
- laa_crime_application_store_app/services/v1/application_service.py
- Moves logic for Get All applications to service layer
- Adds supporting logging
- Provides SecureJsonResponse
N/A
> Move logic to service

- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/secure_json_response.py
- laa_crime_application_store_app/services/v1/application_service.py
- Move get by id logic into service
N/A
> Move get logic to service

- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/services/v1/application_service.py
- Refactor post logic into service
- Add logging to endpoint
N/A
> Move post logic to service

- laa_crime_application_store_app/routers/v1/application.py
- laa_crime_application_store_app/schema/application_update.py
- laa_crime_application_store_app/services/v1/application_service.py
- tests/routers/v1/application_test.py
- Refactor Put logic into service
- Refactor common queries to private methods
- Update to return only 201 from PUT
- Additional logging
N/A
> Move put logic to service

- alembic/README.md
Docs: Update readme re: database setup
Worth explcitly mentioning using the existing `.env.sample`
and how to customize for new devs.
> Docs: Update readme re: database setup

- .circleci/config.yml
- helm_deploy/laa-crime-application-store/values-dev-crm4.yaml
- postman/environments/dev-crm4.postman_environment.json
Add helm and circleci config for deployment to dev-crm4 environment
[CRM457-854](https://dsdmoj.atlassian.net/browse/CRM457-854)
[CRM457-854]: https://dsdmoj.atlassian.net/browse/CRM457-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-854: Add dev-crm4 deployment 

- .circleci/config.yml
Fix name of postman step for dev-crm4
Missed in previous PR
[CRM457-854](https://dsdmoj.atlassian.net/browse/CRM457-854)
[CRM457-854]: https://dsdmoj.atlassian.net/browse/CRM457-854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix name of postman step for dev-crm4

- helm_deploy/laa-crime-application-store/values.yaml
- Removes Swagger endpoint from default values
[CRM457-847](https://dsdmoj.atlassian.net/browse/CRM457-847)
[CRM457-847]: https://dsdmoj.atlassian.net/browse/CRM457-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM456-847 - Remove swagger endpoint from standard values

- helm_deploy/laa-crime-application-store/values-production.yaml
- Add swagger env var to prod
[CRM457-847](https://dsdmoj.atlassian.net/browse/CRM457-847)
[CRM457-847]: https://dsdmoj.atlassian.net/browse/CRM457-847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRM457-847 - Add Swagger endpoint back to prod

- .circleci/config.yml
- bin/deploy
Fix main branch deployment
[CRM457-1166](https://dsdmoj.atlassian.net/browse/CRM457-1166)
[CRM457-1166]: https://dsdmoj.atlassian.net/browse/CRM457-1166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRM457-1166] Fix main branch deployment

- alembic/versions/7adacb84dfbe_use_jsonb.py
- laa_crime_application_store_app/models/application_schema.py
- laa_crime_application_store_app/models/application_version_schema.py
- laa_crime_application_store_app/services/v1/application_service.py
- tests/routers/conftest.py
- tests/routers/v1/application_test.py
* Append events instead of overwriting
* convert JSON fields to JSONB
[CRM457-1145](https://dsdmoj.atlassian.net/browse/CRM457-1145)
[CRM457-1145]: https://dsdmoj.atlassian.net/browse/CRM457-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crm457 1145/event appending

- .circleci/config.yml
- app/controllers/health_controller.rb
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
- Postman `ping` test expects ping endpoint to return some specific stuff in payload
- UAT and prod environments were configured with wrong security settings
- build-and-deploy-open-pr workflow was running on main
> Fix deployment issues

- config/initializers/sentry.rb
- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
- helm_deploy/values-development.yaml
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
Specifiy environment for sentry so it doesn't default to prod
> App store - add environment to sentry config

- app/jobs/notify_subscriber.rb
- spec/jobs/notify_subscriber_spec.rb
At the moment, webhooks involve 2 HTTP requests - the app store worker POSTs the submission ID to the client, and the client GETs the submission from the app store to get full details. The idea was that this would allow flexibility. However, since both clients do the GET synchronously, all this is really doing is adding unnecessary complexity and moving parts. If the submission details are included in the body of the initial POST, that means the GET request can be avoided entirely, making the system faster, easier to reason about and less vulnerable to network issues.
> Send payload inside webhook request

- .circleci/config.yml
Add e2e tests to pipeline
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1396)
So that we can test changes against full flow through app
> CRM457-917: Add circleci config for e2e tests

- helm_deploy/values-development.yaml
> Update app store url

- bin/deploy
Remove debug that was missed in previous merge
[CRM457-1561](https://dsdmoj.atlassian.net/browse/CRM457-1561)
[CRM457-1561]: https://dsdmoj.atlassian.net/browse/CRM457-1561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> rebase and remove debug

- .circleci/config.yml
- helm_deploy/templates/metabase/deployment.yaml
[CRM457-](https://dsdmoj.atlassian.net/browse/CRM457-1362
> CRM457-1362: Scan metabase image before deploy

- helm_deploy/templates/metabase/deployment.yaml
As discussed on slack:
- Pulling in a secret token that will be used to sign iframe URLS
- Force daily reauthentication
> CRM457-1333: Metabase config

- .github/pull_request_template.md
Amend PR template inline with others
> Amend PR template inline with others

- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
[Add TLS cert and custom domain for metabase deployments in app store](https://dsdmoj.atlassian.net/browse/CRM457-1546)
Updates both UAT and Production URLs
> Update Metabase urls to custom domains

- helm_deploy/values-production.yaml
[Metabase Custom Domains](https://dsdmoj.atlassian.net/browse/CRM457-1546)
This is to fix a mistake in my last PR for this
> Metabase custom domains: Fix incorrect url reference (CRM457-1546)

- helm_deploy/templates/metabase/ingress.yaml
Allow our team to view modsec logs for metabase
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1650)
> CRM457-1650: Modsec annotations

- helm_deploy/values-production.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1553)
> CRM457-1553: Enable production metabase

- .circleci/config.yml
Slack notifications on CI failures
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1579)
> CRM457-1579: Add Slack failure notifications

- lib/tasks/missing_version_timestamps.rake
Fix some of the missing data issues (still approx 12 left after these fixes
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1630)
> [CRM457-1630] Rake task to set missing timestamps

- lib/tasks/missing_version_timestamps.rake
Fix to code to deal with incorrect assumption from previous migration
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1630)
> Crm457 1630/missing timestamps 2

- lib/tasks/missing_version_timestamps.rake
When at first you don't succeed... try, try again... :(
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-XXX)
expected output from running on server:
```
skipping record: 155c385e-0ef4-4d5a-813f-ac827d02d2b4: fb8620b4-8c9c-4542-84d5-eef8451c98ee..
skipping record: cfb73028-5531-46df-bcc5-f0fd4a2f7cfd: 7ac70f46-e63e-439b-a8f7-8faa378e56f8..
skipping record: e71f8764-6c30-4ade-b9cc-7007f881ec48: cdf51b41-d633-4a8c-93ee-d2da8494f661..
skipping record: 6d73549a-316c-4b3e-9af6-352030b6fe01: 1f03be18-ed56-4e16-a90f-b40ecb1b2865..
skipping record: 95a18e65-9b97-43aa-af11-008684d3dc47: 4c72a40a-df29-4dce-881e-6b082b1bb234..
skipping record: ee26fbc8-e1b9-49e5-827b-196ed15662a0: de14d863-f3a3-4451-adf3-7d6e3956b963..
skipping record: b0f9423b-71c0-4685-bf84-6dc58bb2a8a6: …
```
> Crm457 1630/missing timestamps 3

- app/models/service_translation.rb
- app/models/translation.rb
- db/migrate/20240708153903_create_service_translations.rb
- db/migrate/20240708153903_service_translations.csv
- db/migrate/20240708160153_update_autogrant_events_to_version2.rb
- db/schema.rb
- db/seeds.rb
- db/seeds/translations.rb
- db/views/autogrant_events_v02.sql
- spec/factories/submission_versions.rb
- spec/factories/submissions.rb
- spec/postgres_views/autogrant_events_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1638)
Add Translated Service Value and Custom Values to Autogrant View
> Crm457 1638 autogrant service

- db/views/version_events_v01.sql
- db/views/version_events_with_times_v01.sql
Restores files previously removed in https://github.com/ministryofjustice/laa-crime-application-store/commit/1e963e18f95484e631dad837fe41698ab42265e1.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1555)
> CRM457-1555: Restore files that were deleted in previous commit

- .github/actions/delete-dev-release/action.yml
- .github/workflows/delete-dev-release.yml
Change name of guthub action and delete redis pvcs
Erroneously named "Delete UAT release".
Delete redis pvc to tidy up and inline with other apps.
> Change name of github action for deleting branches on DEV and delete redis pvcs

- db/migrate/20240716130539_add_last_updated_at_to_applications.rb
a backfill migration failed putting the DB migrations in a tiz, on _dev main only_. 
This will 🤞 fix dev main deployment which is failing atm
> fix other migration due to column existing

- db/migrate/20240716130618_backfill_last_updated_at.rb
another backfill error encounterd
> Fix backfill errors on dev main branch

- db/migrate/20240716130618_backfill_last_updated_at.rb
Fix backfill migration for running against dev main
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1752)
Previous migrations failed with many errors
due to nil events or events without 'created_at'
attributes.
This handles those errors to update the
last_updated_at column for all records regardless.
Will need to be manually rerun on dev main post deploy.
> Handle dirty data on dev main

- Gemfile
- Gemfile.lock
- config/initializers/filter_parameter_logging.rb
- config/initializers/lograge.rb
- spec/spec_helper.rb
Repeat logging improvement from Provider
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1361)
> CRM457-1361: Swap PII for client role

- README.md
- helm_deploy/templates/_helpers.tpl
- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
- helm_deploy/templates/metabase/deployment.yaml
- helm_deploy/values-development.yaml
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
[Check securityContext for all services](https://dsdmoj.atlassian.net/browse/CRM457-1547)
- Put Security Context default settings under a re-usable helper template
- Add information about the settings
> Crm457 1547 security context cleanup

- helm_deploy/templates/metabase/deployment.yaml
[Check securityContext for all services](https://dsdmoj.atlassian.net/browse/CRM457-1547)
To fix deployment errors in UAT and Production
> Remove pod level security context (Metabase)

- lib/tasks/check_autogrants.rake
- spec/factories/submissions.rb
- spec/lib/tasks/check_autogrants_spec.rb
[Status not being updated in JSON blob for expired/autogranted actions from CW](https://dsdmoj.atlassian.net/browse/CRM457-1827)
Task needed for first step of plan to fix data shown [here](https://mojdt.slack.com/archives/C05212WRK5J/p1722954501269829?thread_ts=1722941106.649889&cid=C05212WRK5J)
> Crm457 1827 get faulty submissions (no autogrant event)

- app/services/authorization/rules.rb
- db/migrate/20240808111943_change_sent_back_status_string.rb
- db/schema.rb
- spec/requests/update_submission_spec.rb
Merge alongside matching PRs in other repos
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1784)
> CRM457-1784: Change CRM7 sent_back status name

- db/migrate/20240809094250_back_fill_assessment_comments.rb
- db/schema.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1785)
> CRM457-1785: Backfill assessment comments

- helm_deploy/values-production.yaml
[Upgrade Production Metabase to Match UAT](https://dsdmoj.atlassian.net/browse/CRM457-1856)
> CRM457-1856: Update production metabase image to match uat

- db/migrate/20240819134005_backfill_work_item_position.rb
- db/schema.rb
- lib/data_migration_tools/work_item_position_updater.rb
- spec/factories/work_item.rb
- spec/lib/data_migration_tools/work_item_position_updater_spec.rb
Backfill work item position data
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
Impacts dev main and UAT only currently
> CRM457-1812: Backfill work item position data

- app/models/submission.rb
- app/services/authorization/rules.rb
- app/services/submissions/creation_service.rb
- app/services/submissions/update_service.rb
- db/migrate/20240822122916_make_state_column_consistent.rb
- db/schema.rb
- db/views/searches_v05.sql
- lib/tasks/adjust.rake
- lib/tasks/check_autogrants.rake
- spec/factories/submissions.rb
- spec/lib/tasks/adjust_fix_expired_data.rb
- spec/lib/tasks/adjust_status_spec.rb
- spec/lib/tasks/adjust_update_state_data.rb
- spec/lib/tasks/check_autogrants_spec.rb
- spec/requests/authorization_spec.rb
- spec/requests/create_events_spec.rb
- spec/requests/create_submission_spec.rb
- spec/requests/submissions_search_spec.rb
- spec/requests/update_submission_spec.rb
Rename state column for consistency
Remove 'provider_requested' status
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1803)
> CRM457-1803: Make state consistent

- .rubocop.yml
- lib/tasks/fixes.rake
- spec/factories/application.rb
- spec/factories/submission_versions.rb
- spec/factories/submissions.rb
- spec/lib/tasks/fixes_spec.rb
Add take task to update contact email address
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1909)
Part of documenting undeliverable email handling
> CRM457-1909: Add rake task to update contact email address

- helm_deploy/templates/metabase/ingress.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-XXX)
> CRM457-2069: Add exception

- config/database.yml
- helm_deploy/templates/deployment-worker.yaml
- helm_deploy/templates/deployment.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1759)
> CRM457-1759: Use full SSL verification for RDS

- app/jobs/notify_subscriber.rb
There are some errors we haven't been catching but should
And the logic was a little hard to follow
> Raise more errors and clarify what is going on

- db/migrate/20241031110650_update_submissions_by_dates_to_version_3.rb
- db/schema.rb
- db/views/submissions_by_date_v03.sql
- spec/postgres_views/submissions_by_date_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2176)
> CRM457-2176: Update view definition for submission_by_date to handle CRM4 resubmissions

- .circleci/config.yml
- .snyk
- helm_deploy/values-uat.yaml
Resolves a CVS identified by Snyk that could cause a denial of service.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2161)
> CRM457-2161: Pull Metabase docker tag from config in CI

- .circleci/config.yml
- helm_deploy/values-production.yaml
> Update Metabase from v0.50.24.4 to v0.51.1.5

- db/migrate/20241105091753_add_assignment_fields_to_application.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2216)
> Fix broken migration

- Gemfile
- Gemfile.lock
- app/controllers/V1/submissions_controller.rb
- app/services/authorization/rules.rb
- app/services/submissions/auto_assignment_service.rb
- config/routes.rb
- db/migrate/20241105091753_add_assignment_fields_to_application.rb
- spec/requests/auto_assignments_spec.rb
Add an endpoint to allow automatic assignment of an appropriate submission to the provided user
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2216)
> CRM457-2216 part 3: Auto assignments

- config/sidekiq.yml
It looks like we've added a new queue for the expire application cron job but we're not telling our workers about it
> Add pooling queue to Sidekiq config

- Gemfile
- Gemfile.lock
related to change https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1311
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2282)
> [CRM457-2282] bump common gem

- app/services/submissions/creation_service.rb
- spec/requests/create_submission_spec.rb
So that if something goes wrong creating a submission we don't leave behind some incomplete records
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2339)
> CRM457-2339: Wrap creation calls in a transaction

- lib/tasks/CRM457_2154.rake
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2154)
To ensure that we don't modify CRM4 records on a process intended for CRM7s only
> CRM457-2154: Filter rake task for adding high value

- lib/tasks/CRM457_2154.rake
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2154)
[Context here
](https://mojdt.slack.com/archives/C06AB6RDY2W/p1734541463038549)
> CRM457-2154: High value rake task - actually update the application hash

- db/migrate/20241220151833_update_processing_times_to_version_2.rb
- db/migrate/20241220153056_update_submissions_by_dates_to_version5.rb
- db/migrate/20241220153455_update_submission_by_services_to_version_5.rb
- db/schema.rb
- db/views/processing_times_v02.sql
- db/views/submission_by_services_v05.sql
- db/views/submissions_by_date_v05.sql
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2361)
- This is needed because otherwise some of our metrics will double count
> Crm457 2361 filter pending versions for analytics views

- .rubocop.yml
- config/application.rb
- config/environments/production.rb
- config/initializers/govuk_notify.rb
- config/initializers/lograge.rb
- config/initializers/prometheus.rb
- config/initializers/schema_fix.rb
- config/initializers/sentry.rb
- config/initializers/sidekiq.rb
- config/routes.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2353)
> Crm457-2353: Rubocop cleanup

- .snyk
At this rate it looks like these just won't ever be handled, and we don't use either of the drivers affected.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2367)
> Add more Snyk ignores

- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2408)
> CRM457-2408: Wrap pool size vars into string

- helm_deploy/templates/metabase/deployment.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2408)
Previous PR didn't fix the problem
> CRM457-2408: Wrap Pool Values in Quotes

- lib/tasks/CRM457_2403.rake
- spec/lib/tasks/crm457_2403_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2403)
- Include what last_updated_at was before change
- Add counter for records that should have updated count
- Add counter for records that updated count
> Crm457-2403: Enhance logs for rake task

- Gemfile
- Gemfile.lock
bump common gem
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1792)
> [CRM457-1792] bump common gem

- app/jobs/nsm/delete_reviewed_claim_docs.rb
- spec/jobs/nsm/delete_reviewed_claim_docs_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2428)
> [CRM457-2428] scope GDPR redaction to file_name

- Gemfile
- Gemfile.lock
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2388)
> CRM457-2388: Bump common gem version

- Gemfile
- Gemfile.lock
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2444)
- Update LAA Crime Forms Common from v0.10.0 to v0.10.1
[Example of how to create discrepency here](https://coconut-halibut-07b.notion.site/Work-Item-Rounding-Example-1d6a3b77972880b19454fc39c50ea832?pvs=74)
> CRM457-2444: NSM: QA Amended calculations removing rounding discrepancy

- Procfile.dev
- README.md
Add a little note about setting up debugging and making it easier to
turn on/off
[Link to relevant discussion](https://mojdt.slack.com/archives/C05212WRK5J/p1746618129624309)
> Enable debugging setup

- db/migrate/20250512140556_update_submission_creation_times_to_version_2.rb
- db/schema.rb
- db/views/submission_creation_times_v02.sql
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2514)
> CRM457-2514: Add office code to submission creation view

- helm_deploy/templates/metabase/ingress.yaml
Reduce the Metabase anomaly threshold
> Reduce the Metabase anomaly threshold

- .snyk
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
update metabase docker image to latest image 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-XXX)
> Update metabase image

- .rspec
- Gemfile
- Gemfile.lock
- README.md
- config/database.yml
- config/environments/test.rb
- spec/flatware_helper.rb
- spec/lib/analytics_creator_spec.rb
- spec/spec_helper.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2622)
> Add flatware to enable async test running

- bin/deploy
- helm_deploy/templates/_helpers.tpl
- helm_deploy/templates/metabase/ingress.yaml
- helm_deploy/values-production.yaml
- helm_deploy/values-uat.yaml
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2671)
Can only test once merged so that it can get to UAT
> CRM457-2671: Re-enable Metabase with IP Address Whitelist

- db/migrate/20250717134112_add_allowed_assigned_counsel_costs.rb
- db/schema.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2683)
Adding allowed versions for each assigned counsel payment cost
> CRM457-2683: Add allowed costs to assigned counsel payments

- Gemfile
- Gemfile.lock
- app/controllers/V1/payment_requests_controller.rb
- app/resources/assigned_counsel_claim_resource.rb
- app/resources/nsm_claim_resource.rb
- app/resources/payment_request_resource.rb
- app/services/authorization/rules.rb
- config/routes.rb
- spec/requests/show_payment_request_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2698)
> CRM457-2698 GET payment request

- app/controllers/V1/nsm_claims_controller.rb
- app/models/assigned_counsel_claim.rb
- app/models/nsm_claim.rb
- app/services/authorization/rules.rb
- app/validators/office_code_validator.rb
- config/locales/errors.yml
- config/routes.rb
- spec/requests/update_nsm_claim_spec.rb
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2693)
> CRM457-2693 PATCH nsm_claims

- app/services/payment_requests/search_service.rb
Needed for the index view in Assess
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2688)
> Allow sorting by firm_name

- bin/deploy
- helm_deploy/values-development.yaml
Correctly set the repository for postgres & redis to allow us to get updates
> Set the needed values for using bitnami legacy
