ministryofjustice/laa-crime-application-store

Pipfile
Pipfile.lock
laa_crime_application_store_app/main.py
laa_crime_application_store_app/middleware/secure_headers_middleware.py
tests/middleware/secure_headers_middleware_test.py

- Adds a Secure headers middleware so that we can adhere to security standards. 
[CRM457-361](https://dsdmoj.atlassian.net/browse/CRM457-361)
This has been replicated from laa-court-data-api as this went through DAST scanning and it was noted as a vulnerability
[CRM457-361]: https://dsdmoj.atlassian.net/browse/CRM457-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRM456-361 - Add SecureHeadersMiddleware

---

alembic/versions/4728f5eac46d_add_events_to_claim.py
laa_crime_application_store_app/models/application.py
laa_crime_application_store_app/models/application_new.py
laa_crime_application_store_app/models/application_update.py
laa_crime_application_store_app/routers/v1/application.py
laa_crime_application_store_app/schema/application_schema.py

Add events storage and retrieval to application object
[CRM457-549](https://dsdmoj.atlassian.net/browse/CRM457-549)
[CRM457-549]: https://dsdmoj.atlassian.net/browse/CRM457-549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[CRM457-549] Add events to main claim object and allow update via post/put

---

.circleci/config.yml

Modify pipeline to separate test workflows out
So we can build and deploy changes to this
datastore in a similar manner to its "frontends"
- laa-claim-non-standard-magistrate-fee-backend
- laa-assess-non-standard-magistrate-fee
test:
build and deploy:
test build and deploy

Separate test workflows out

---

laa_crime_application_store_app/services/v1/application_service.py

Clean up logs used to debug claim submission process
Consistently add logs for when db transactions are happening
No Ticket

Clean Up Logs

---

Dockerfile

[To fix Snyk issue]( https://security.snyk.io/vuln/SNYK-ALPINE318-EXPAT-6241039)

force apk installation for expat version 2.6.0-r0 or higher

---

.env.sample
README.md

Add documentation and sample for expected env vars
Not having the APP_CLIENT_ID, TENANT_ID
secrets will cause the server to timeout
locally
Not having the SWAGGER_ENDPOINT var
means you will not be able to get to
the swagger docs `/docs` locally.

Add documentation about env vars

---

Dockerfile

This is an update to the Docker image to try and fix the error when it doesn't build on an M1 machine. See comment on this stackoverflow.
https://stackoverflow.com/a/71372163
[CRM457-919](https://dsdmoj.atlassian.net/browse/CRM457-919)
[CRM457-919]: https://dsdmoj.atlassian.net/browse/CRM457-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRM457-919-Update docker file to fix M1 issue

---

.circleci/config.yml

Automate deployment to prod for main
Until we go to private beta, and perhaps even after that,
we might as well deploy to UAT and then production automatically.
This will:
expose any deployment issues immediately on a per merge basis
not incur overhead of devs remembering to deploy
Have taken opportunity to remove some unreached steps and rename jobs

Automate Deployment to Main

---

.circleci/config.yml
app/controllers/health_controller.rb
app/jobs/notify_subscriber.rb
app/services/tokens/verification_service.rb
config/puma.rb
helm_deploy/values-production.yaml
helm_deploy/values-uat.yaml
spec/jobs/notify_subscriber_spec.rb
spec/requests/create_submission_spec.rb

- Another fix to ping endpoint to match postman expectations
- Handle Socket::ResolutionError the same way as other errors in NotifySubscriber
- Bump UAT and production pod resources to be able to handle a `rails c` alongside ` rails s`
- Allow puma to launch in cluster mode so we can handle a synchronous response to our webhook callbacks in E2E tests
- Use fallback request header to identify client role in non-auth setup.

CRM457-1327: More fixes

---

app/controllers/V1/submissions_controller.rb
app/controllers/V1/subscribers_controller.rb
app/controllers/application_controller.rb
app/controllers/health_controller.rb
app/services/authorization/rules.rb
app/services/authorization_service.rb
app/services/submissions/update_service.rb
spec/requests/authentication_spec.rb
spec/requests/authorization_spec.rb
spec/requests/delete_subscriber_spec.rb
spec/requests/update_submission_spec.rb

- Add a set of rules of what providers and caseworkers can do
- Include what states they can change submissions to and from
- Authorize in a before_action according to the rules
[CRM457-1146](https://dsdmoj.atlassian.net/browse/CRM457-1146)
[CRM457-1146]: https://dsdmoj.atlassian.net/browse/CRM457-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRM457-1146: Add authorization rules

---

app/services/tokens/verification_service.rb
helm_deploy/templates/deployment-worker.yaml
helm_deploy/templates/deployment.yaml
spec/requests/authentication_spec.rb
spec/requests/authorization_spec.rb

Our Entra tokens now contain a "roles" array populated with either `["Provider"]` or `["Caseworker"]`. Using this means we don't need the app store to know the specific client IDs used by provider/caseworker apps, giving us more flexibility.

Use roles instead of knowing specific IDs

---

helm_deploy/templates/deployment-worker.yaml

How to verify this fixes stuff:
```
kubectl get pods -n laa-crime-application-store-dev
```
Pick any healthy pod that is neither named `routing-label` nor `laa-crime-application-store-app` and then run
```
kubectl exec -it <pod name> -n laa-crime-application-store-dev -- sh
```
From your shell, if you run the following several times, instead of giving you a 401 every time, it will sometimes give you a "connection refused" error:
```
wget http://laa-crime-application-store-app.laa-crime-application-store-dev.svc.cluster.local
```
This shows that on dev main (with service name `laa-crime-application-store-app`), requests that bypass the ingress are sometimes being routed to worker pods instead of web app pods.
However, if you instead run
```
wget …
```

Change labels on worker deployment

---

helm_deploy/values-development.yaml

False positives break stuff, dev is a low-security environment, and we don't have modsec in UAT or prod anyway due to not having ingresses there.

Disable modsec in dev

---

helm_deploy/templates/hpa-worker.yaml
helm_deploy/templates/hpa.yaml
helm_deploy/values-development.yaml
helm_deploy/values-production.yaml
helm_deploy/values-uat.yaml

Add horizontal pod autoscaler (HPA) config
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1456)
To handle scaling up/down based on CPU and memory usage.
Needs to go in after the following cloud platform PRs, which add the necessary serviceaccount permissions
https://github.com/ministryofjustice/cloud-platform-environments/pull/22945
https://github.com/ministryofjustice/cloud-platform-environments/pull/22946
https://github.com/ministryofjustice/cloud-platform-environments/pull/22947

CRM457-1456: Add horizontal pod autoscaler (HPA) config

---

.circleci/config.yml
bin/deploy
helm_deploy/templates/deployment-worker.yaml
helm_deploy/templates/deployment.yaml
helm_deploy/templates/metabase/deployment.yaml
helm_deploy/templates/metabase/ingress.yaml
helm_deploy/values-development.yaml
helm_deploy/values-production.yaml
helm_deploy/values-uat.yaml

[CRM457-1561](https://dsdmoj.atlassian.net/browse/CRM457-1561)
Modsec in basic setup doesn't permit metabase to work. Rather than switch it off completely have mirrored the setup from  [crime apply](https://github.com/ministryofjustice/laa-criminal-applications-datastore/blob/fde2f61b8002e6de5bf1e943673805e554d3875b/config/kubernetes/metabase/ingress.yml#L19) but adjusted the parameters to match the settings we have for modsec in dev of [laa-assess-crime-forms](https://github.com/ministryofjustice/laa-assess-crime-forms/blob/356031514a6a221fcc4b0762e884cc5d97d91eeb/helm_deploy/values-dev.yaml#L29)
Note that this is the same as other environments except for the filesize limit which should be updated to be the same as dev.
Also 
- updated deprecated deploy step to run
- added extra time for …

Crm457 1561 fix modsec on metabase

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/initializers/prometheus.rb
helm_deploy/dashboards/grafana-golden-signals.yml
helm_deploy/dashboards/grafana-rails-metrics.yml
helm_deploy/templates/_helpers.tpl
helm_deploy/templates/deployment.yaml
helm_deploy/templates/service.yaml
spec/spec_helper.rb

- Add some Grafana dashboard definitions
- On all PR merges, (re-)apply Grafana config maps
- On web app pod Rails boot, start a prometheus server and feed it relevant data
[CRM457-1457](https://dsdmoj.atlassian.net/browse/CRM457-1457)
[Golden signals dashboard](https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-crime-store-grafana-golden/laa-non-standard-crime-claims-golden-signals?orgId=1&refresh=5m) | [Rails metrics dashboard](https://grafana.live.cloud-platform.service.justice.gov.uk/d/laa-crime-store-grafana-metrics/laa-non-standard-crime-claims-rails-metrics?orgId=1&refresh=5m&var-datasource=prometheus&var-namespace=laa-crime-application-store-dev&var-controller=All&var-action=All)
If we're happy with this approach, I'll need to update our other 2 apps to export …

CRM457-1457: Grafana

---

helm_deploy/dashboards/grafana-rails-metrics.yml

Accommodate different healthcheck controller names across apps (in provider and caseworker the health controller is called healthcheck, not health)
[CRM457-1457](https://dsdmoj.atlassian.net/browse/CRM457-1457)
[CRM457-1457]: https://dsdmoj.atlassian.net/browse/CRM457-1457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CRM457-1457: Grafana tweak

---

.circleci/config.yml

[End to End tests block deployment to production](https://dsdmoj.atlassian.net/browse/CRM457-1578)
Ticket only explicitly says to block deployment to production but decided to also block deployment to dev and uat because otherwise we have to manually rollback afterwards and we shouldn't have faulty code in UAT

End to End Test Required to Pass Before any Deployment

---

db/schema.rb

Apply the view creations fully to schema
[CRM457-](https://dsdmoj.atlassian.net/browse/CRM457-1487)
Running the migrations with none to run amends the views to
remove the table prefixes, as they are unnecessary.
This just commits this change to the repo.

Apply the view creations fully to schema

---

helm_deploy/templates/metabase/ingress.yaml
helm_deploy/values-production.yaml
helm_deploy/values-uat.yaml

[Add TLS cert and custom domain for metabase deployments in app store](https://dsdmoj.atlassian.net/browse/CRM457-1546)
The TLS certificate had been created but not associated to ingress - this fixes that

Associate TLS certificate to metabase ingress

---

helm_deploy/templates/metabase/ingress.yaml

We have been experiencing some ModSec false positives, and we are aware of other teams experiencing them. This PR disables some of the more unreliable rules:
Civil Apply [found](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/3686039762/ModSecurity) that this was triggering if "a user ends a sentence with get and a single word, followed by a new line"
We [found](https://mojdt.slack.com/archives/C06UR7V28RZ/p1718890420747279) that this was triggering if a string in a JSON payload contained two consecutive pairs of parentheses, such as "...The preparation hourly rate has been reduced as per Schedule 1 of The Criminal Legal Aid (Remuneration)(Amendment) Regulations 2022..."
Crime Apply [found](https://github.com/ministryofjustice/cla_public/pull/1238) that this was triggering on a …

CRM457-1657: Remove some modsec false positives

---

app/controllers/V1/events_controller.rb
app/controllers/V1/submissions_controller.rb
app/services/authorization/rules.rb
app/services/submissions/update_service.rb
config/routes.rb
spec/requests/authorization_spec.rb
spec/requests/create_events_spec.rb
spec/requests/update_submission_spec.rb

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1664)
When looking at this I initially planned to add a new endpoint, but when looking at the existing code I realised it was already allow (almost) in the current endpoint so chose to modify the rules instead.
Happy to chnage to have a separate endpoint if people feel strongly

[CRM457-1664] allow events only to be updated

---

Dockerfile
config/initializers/prometheus.rb
config/initializers/sidekiq.rb
helm_deploy/templates/_helpers.tpl
helm_deploy/templates/deployment-worker.yaml
helm_deploy/templates/deployment.yaml
helm_deploy/templates/network-policy.yaml
helm_deploy/templates/service-monitor.yaml
helm_deploy/templates/service.yaml

Add sidekiq metrics to prometheus
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1360)
To visualize and alert on as required
- You can test standard metrics are available on the branch using [this prometheus query](https://prometheus.cloud-platform.service.justice.gov.uk/graph?g0.expr=avg(ruby_http_request_duration_seconds%7Bnamespace%3D%22laa-crime-application-store-dev%22%7D)&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=12h)
- You can test sidekiq metrics are available on the branch using [this prometheus query](https://prometheus.cloud-platform.service.justice.gov.uk/graph?g0.expr=ruby_sidekiq_stats_processed%7Bnamespace%3D%22laa-crime-application-store-dev%22%7D&g0.tab=0&g0.display_mode=lines&g0.show_exemplars=0&g0.range_input=1h)

CMR457-1360: Add sidekiq metrics

---

app/services/submissions/update_service.rb
db/migrate/20240628155626_missing_event_fields.rb
db/schema.rb
db/seeds.rb
spec/requests/create_events_spec.rb

Ensure version, created_at adn updated_at are set on all events (on creation)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1630)
Ideally the provider_updated event should also have a user ID on it... but this is not a app store concern so have left out for now... this would also likely break the CW app as they wouldn't know the user ID

Crm457 1630/fix broken events

---

.circleci/config.yml

Change snyk docker scanning approach
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1529)
This implements all but the IaC scan. The reason for not implementing IaC scanning now is:
- IaC needs rendered terraform or k8s manifests to scan, not helm templates
- attempts to render the manifests and pass them to the `snyk IaC test` hit various problems to do with helm install on test-executor (overcome), requiring k8s login for rendering the manifest (requiring cloud-platform-executor) or snyk install on cloud-platform-executor, and it has not been possible to test whether a helm upgrade --dry-run output would work. Certainly a `helm template blah` command as suggested by snyk docs is insufficient in our case. Ideally the cloud-platform-executor would have snyk installed …

CRM457-1529: Change snyk scanning approach

---

app/models/search.rb
db/migrate/20240703123137_create_searches.rb
db/migrate/20240703161618_add_virtual_columns.rb
db/migrate/20240703183137_create_searches.rb
db/migrate/20240708131924_stupid_forward_slash.rb
db/schema.rb
db/views/searches_v01.sql
spec/factories/application.rb
spec/factories/submission_versions.rb
spec/factories/submissions.rb
spec/models/search_spec.rb

[SPIKE Caseworker: Search and filter - required changes to datastore](https://dsdmoj.atlassian.net/browse/CRM457-1713)
- Searches table uses virtual fields to collate search keywords for a given application
- UFN and LAA Reference are special cases as the tsvector functions consider a dash followed by a number a negative number and a slash as an escape so these are searched via the original fields
* we are using weights to split how searching works. 
- Items with a weight of A require a full match
- items with a weight of B match the start of string only
* using regexp to remove `-` character from LAA reference to simplify matching
* two know edgecases that don't match when maybe the should:
- names with a dash followed by a number ie. `Palace Court-1` these will match on `palace`, …

Crm457 1713 - SPIKE Caseworker: Search and filter - required changes to datastore

---

lib/tasks/db.rake
run.sh

Sometimes 2 pods run migrations at the same time, one loses the race, and we get error messages on Slack even though nothing bad has happened. This should prevent those false positives.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1672)

CRM457-1672: Concurrent migrations

---

spec/factories/translation.rb
spec/postgres_views/autogrant_events_spec.rb

[Analytics Dashboard: Autogrant](https://dsdmoj.atlassian.net/browse/CRM457-1638)
Adds factory for translations and loads translation needed for tests as factory instead of relying on it being in the table in case a developer doesn't have the data in their test db (this can happen when the db already exists when db:prepare is run)

Crm457 1638 fix autogrant view tests

---

spec/postgres_views/autogrant_events_spec.rb

Use find_or_create_by to avoid issue of local setup not having seeds, but it they do standard factory create will error out on primary key uniqueness issues.

Use find or create by

---

lib/tasks/adjust_status.rake
spec/lib/tasks/adjust_status_spec.rb
spec/spec_helper.rb

We need to fix some data in the provider app, and rather than manually fix it in every other database we can push through an updated payload. BUT to do so we need to temporarily put affected submissions into a state that permits provider updates. This task lets us do this. Intended usage:
- Identify affected IDs in provider
- Use this to set status of those to `sent_back` WITHOUT sending notifications
- Run the fix in provider
- Use this to set the status of them back to their initial state, sending notifications to caseworker to make sure it ends up tracking the correct state.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1747)

CRM457-1747: Task to adjust status

---

helm_deploy/templates/metabase/ingress.yaml

951220, "mssql SQL Information Leakage"
Redundant because we don't use mssql. False positives happening in the wild (so far only on the app store metabase)
952100, "Java Source Code Leakage"
Redundant because we don't use Java. False positives happening on our javascript sourcemaps

CRM457-1721: More modsec false positives

---

app/services/submissions/creation_service.rb
app/services/submissions/update_service.rb
db/migrate/20240716130539_add_last_updated_at_to_applications.rb
db/migrate/20240716130618_backfill_last_updated_at.rb
db/schema.rb
spec/requests/create_submission_spec.rb
spec/requests/update_submission_spec.rb

Add last_updated_at column, backfill and populate on submission create or update
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1715)
To allow searching and filtering on a top level
date value.

CRM457-1715: Add last_updated_at column, backfill and populate on submission create or update

---

db/migrate/20240716130618_backfill_last_updated_at.rb

fix error in migration 
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-XXX)
```rb
Caused by:
NoMethodError: undefined method `to_time' for nil (NoMethodError)
latest_event = submission.events&.max_by { |event| event['created_at'].to_time }
^^^^^^^^
```

fix undefined method error in migration

---

app/models/search.rb
spec/models/search_spec.rb

A search query with a leading space was causing a 422 error from the app store. While arguably the client should strip whitespace, the app store shouldn't error out with a postgres error if it doesn't.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1761)

CRM457-1761: Cope with leading spaces

---

.snyk

Ignore CVE warning `SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538`
Unblock CI until a fix or workaround is available.

Ignore CVE warning `SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538`

---

.circleci/config.yml

Remove unneeded circleci step
We are scanning the metabase image not the apps's built
image.

Remove unneeded circleci step

---

.circleci/config.yml
.yamllint
helm_deploy/templates/deployment-worker.yaml

[Last outcome for this ticket](https://dsdmoj.atlassian.net/browse/CRM457-1547)
Note: this runs helm lint AND helm template (debug) because from my experience helm lint won't always necessarily catch issues that can break a chart (I tested helm lint on some misconfigurations and it didn't catch some of them) where helm template will AND helm template doesn't give us warning level suggestions like helm lint does - so both in tandem covers all bases for breaking changes and suggestions
Also including yamllint to check for things like duplicate keys upon suggestion from @elken[ in this PR](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1013)

Add additional helm chart/yaml linting

---

app/controllers/V1/events_controller.rb
app/services/submissions/event_addition_service.rb
app/services/submissions/update_service.rb

Move event addition into its own service (calling it addition, not creation, because the service doesn't persist anything to the database), since it has its own area of responsibility that is now needed by multiple other things
Lock the record in the event creation endpoint
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1844)

CRM457-1844: Refactor out event additions and lock it

---

db/migrate/20240806130123_backfill_disbursement_position.rb
db/schema.rb
lib/data_migration_tools/disbursement_position_updater.rb
spec/factories/disbursements.rb
spec/lib/data_migration_tools/disbursement_position_updater_spec.rb

Backfill NSM claim disbursements to have positions
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1812)
Inline with designs on submit and assess for displaying
disbursements in a specific order.
Should be merged shortly after [this submit PR](https://github.com/ministryofjustice/laa-submit-crime-forms/pull/1039)

CRM457-1812: Backfill NSM claim disbursements to have positions

---

db/migrate/20240807164119_fix_missing_autogrant_events.rb

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1827)
For the 5 submissions that have missing autogrant events ([found via task added in this PR](https://github.com/ministryofjustice/laa-crime-application-store/pull/241)) add accurate event data from assess-crime-forms-prod to events 
(Each event json output found via calling: `Submission.find('<submission_id>').events.filter{_1[:event_type] == "Event::NewVersion"}.as_json` in assess-crime-forms-prod)

Crm457 1827 fix faulty autogrants

---

app/jobs/notify_subscriber.rb

retry_on is part of the ActiveJob DSL that causes errors to be swallowed until a certain number of retries, after which the error is allowed to bubble up to the underlying mechanism (in our case Sidekiq, which will report the error to Sentry) This isn't actually the behaviour we want - if a job is failing we want Sentry to be informed immediately the first time it fails, on the grounds that normally this is going to be the indication of a problem, not some harmless transient error, so we want as much heads up as possible.

CRM457-1847: Remove 'retry_on'

---

app/services/authorization/rules.rb
app/services/submissions/creation_service.rb
spec/requests/create_submission_spec.rb

We found an issue where submissions were sent to the app store with status 'draft'. But we didn't spot it immediately because we were silently 'correcting' the status in the state field, but not in the "blob".  Let's be more picky, and fail out immediately if we spot impermissible data
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-1905)

CRM457-1905: Check submission state

---

spec/lib/tasks/adjust_fix_expired_spec.rb
spec/lib/tasks/adjust_fix_provider_updated_spec.rb
spec/lib/tasks/adjust_update_state_spec.rb
spec/lib/tasks/fixes_spec.rb
spec/rails_helper.rb

Silence output to console from testing of rake tasks
Rake tasks often having stdout output but this comes
out when running rspec and clutters the console.

Swallow output to stdout during tests for rake tasks

---

lib/tasks/fixes.rake
spec/factories/submission_versions.rb
spec/lib/tasks/find_mismatched_references_spec.rb
spec/rails_helper.rb

[Part 1 of ticket](https://dsdmoj.atlassian.net/browse/CRM457-1966)
Task generates a list of submissions that have mismatched laa_references between versions, shows the original version's reference and a list of all the references associated
The results will be used for each of the data fixing tasks in all the service dbs so we can associated the submissions with their original version

Crm457 1966 find incorrect refs

---

lib/tasks/fixes.rake
spec/lib/tasks/auto_fix_mismatched_references_spec.rb
spec/lib/tasks/find_mismatched_references_spec.rb
spec/lib/tasks/fix_mismatched_references_spec.rb

[Part 3 - Fix Records in App Store](https://dsdmoj.atlassian.net/browse/CRM457-1966)
- Fixes app store SubmissionVersions in RFI where laa_reference doesn't match between version (applies original laa_reference to all versions)
- Has a manual version that doesn't use check in case we need to use that

Crm457 1966 fix incorrect refs

---

app/controllers/V1/submissions_controller.rb
app/services/authorization/rules.rb
app/services/submissions/metadata_update_service.rb
config/routes.rb
spec/requests/update_submission_metadata_spec.rb

So we can sync back risk updates to the app store.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2066)

CRM457-2066: Allow metadata updates

---

app/services/authorization/rules.rb

Because caseworkers need to generate assignment events for sent-back NSM claims (for claims that are sent back before NSM RFI loops are implemented so do not enter `provider_updated` status when the provider has emailed through their updates.)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2090)

CRM457-2090: Loosen event appending rules

---

app/jobs/notify_subscriber.rb
db/migrate/20241015101440_add_notify_subscriber_completed_to_submissions.rb
db/schema.rb
spec/jobs/notify_subscriber_spec.rb

Set a flag before running an async job, change the flag after running it, that way if we lose access to Redis (both the job queue and the logs of dead jobs), we know what needs to be re-synced.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2095)

CRM457-2095: Add flags indicating async job status

---

app/jobs/notify_subscriber.rb
app/services/notification_service.rb
app/services/submissions/creation_service.rb
app/services/submissions/update_service.rb
spec/jobs/notify_subscriber_spec.rb

So that if there's a Redis issue we won't end up in an inconsistent state.
Note a few refactorings to make sure things stay locked in the right places etc
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2094)

CRM457-2094: Make job enqueueings atomic

---

db/seeds.rb
lib/tasks/db.rake

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2195)
Moves db:seed steps to db:preparation:run_with_retry because db:seed only runs if database doesn't already exist

Fix Analytics User Rights and Translations Not Getting Updated

---

db/migrate/20241105152058_update_submission_by_services_to_version_3.rb
db/schema.rb
db/views/submission_by_services_v03.sql

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2194)
Return the Service Type column as text instead of JSON representation to avoid unnecessary speech marks

Return service column as text instead of json representation

---

app/models/search.rb
spec/requests/submissions_search_spec.rb

An issue was raised in which PG doesn't like having unmatched brackets and other statements in the search query, so we attempt to remove them first.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2214)

CRM457-2214: Sanitize the search query first

---

app/services/submissions/search_service.rb
spec/requests/submissions_search_spec.rb

The 'your claims' view in caseworker allows sorting by risk, so search now supports it. Except that it was broken because risk_level is an integer in the view, and we were calling "LOWER" on it
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2216)

CRM457-2216: Fix bug in sorting by risk level

---

app/controllers/V1/adjustments_controller.rb
app/services/authorization/rules.rb
app/services/submissions/adjustment_service.rb
app/services/submissions/event_addition_service.rb
app/services/submissions/update_service.rb
config/routes.rb
db/migrate/20241111091017_add_pending_to_application_version.rb
db/schema.rb
spec/requests/adjust_submission_spec.rb
spec/requests/create_events_spec.rb
spec/requests/update_submission_spec.rb

The app store needs to be able to hold onto the state of a submission as each adjustment is made by the caseworker without bumping the submission version each time. It achieves this by putting everything in a "pending" version that can be built up over time and eventually replaced by the full new version.
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2216)

CRM457-2216 part 4: Allow storage of pending (mid-adjustments) states and non-timestamp-affecting events

---

app/controllers/V1/submissions_controller.rb
app/services/notification_service.rb
app/services/submissions/creation_service.rb
app/services/submissions/update_service.rb
spec/requests/create_submission_spec.rb
spec/requests/update_submission_spec.rb

- Notify subscribers synchronously
- For autogrants, let provider app know by putting new state in response
- Now the only things we use sidekiq for are autogrant emails and triggering the expiry cron job
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2276)

CRM457-2276: Stop relying on Sidekiq

---

app/controllers/V1/submissions/searches_controller.rb
app/services/authorization/rules.rb
app/services/submissions/search_service.rb
db/migrate/20241125171006_update_searches_to_version_7.rb
db/schema.rb
db/views/searches_v07.sql
spec/requests/authorization_spec.rb
spec/requests/submissions_search_spec.rb

- Providers can access the search endpoint
- The search endpoint allows passing in multiple office codes
- Searches can be sorted by UFN
- Searches can be sorted by the date of the most recent state change (e.g. for submitted applications it's when they were submitted, not the date of the most recent caseworker assignment)
- Caseworker app can no longer subscribe/unsubscribe (since it doesn't do that any more)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2221)

CRM457-2221: Allow providers to generate filtered lists

---

Gemfile
Gemfile.lock
README.md
bin/delete_anonymised
bin/download_anonymised
lib/tasks/anonymised.rake
spec/lib/tasks/anonymised_data_spec.rb

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2322)
Note that this is a first step towards pulling records from prod into a secure pre-prod environment, but it delivers incremental usefulness as a standalone step.

CRM457-2322 part 1: Pull anonymised records from prod to localhost

---

Gemfile
Gemfile.lock
app/controllers/V1/submissions/searches_controller.rb
app/controllers/V1/submissions_controller.rb
app/models/submission.rb
app/services/submissions/search_service.rb
db/migrate/20241211102459_make_risk_optional.rb
db/schema.rb
spec/requests/create_submission_spec.rb
spec/requests/show_submission_spec.rb
spec/requests/update_submission_metadata_spec.rb
spec/services/submissions/search_service_spec.rb

Allow the gem to handle setting risk and high_value flags
Bonus: Ensure that the provider app never sees work-in-progress adjustments by a caseworker (I don't think this is a bug at the moment, but we're relying on the provider app _hiding_ these adjustments, which it shouldn't have to do)
[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2335)

CRM457-2335: Risk and value setting

---

config/initializers/schema_fix.rb
db/schema.rb

If you've run `rails db:migrate` recently you'll see that the schema file gets messed up by including a bunch of postgis tables, which then cause tasks like `rails db:prepare` to explode. As a result, the schema file has been getting rather out of date. So I've:
- Added a workaround for the postgis issue and a comment explaining how/when it can be resolved properly
- Run the migrations from scratch on a clean database so that the schema file accurately represents what should currently be in production
This should mean that future migrations should only change the schema file in the normal ways.

Get schema file under control

---

helm_deploy/templates/metabase/deployment.yaml

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2408)
This is an attempt to fix issues with dashboards not loading, more information[ in this thread](https://mojdt.slack.com/archives/C05212WRK5J/p1737717395420209)
The error seems to be related to db connection pooling and could indicate that there are too many threads open on the connection for Metabase's JDBC to handle, so we're increasing the number of available threads on the JDBC.

CRM457-2408: Increase db connection pool size from default (15) to 25

---

db/migrate/20250514155430_update_submission_creation_times_to_version_3.rb
db/schema.rb
db/views/submission_creation_times_v03.sql

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2455)
To fix erroneous records being added to view since a new version is created for each assignment
Only retrieves the first submitted version for a given application id 
[This rectifies issue found here
](https://mojdt.slack.com/archives/C034YPREUSF/p1747236841024359?thread_ts=1747213061.572249&cid=C034YPREUSF)

Update submission_creation_times to ignore assignment versions

---

db/migrate/20250514090602_create_submission_assess_times.rb
db/schema.rb
db/views/submission_assess_times_v01.sql

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM456-2519)
Adds new view for assessment times with per application: 
- application id
- office code
- application type
- submission_date (created_at of application record) 
- first decision (the status of the first application_version record that has a application->status of a decision state)
- first decision date (the created_at of the first application_version record that has a application->status of a decision date)
- first assigned date (the created_at of the first assignment event on the application's caseworker_history_events array)
- minutes to assign (difference between submission date and first assigned date in minutes) 
- minutes to assess (difference between first assigned date and first decision date in minutes)

CRM456-2519: Create Metrics Report for Time To Assess A Claim

---

db/migrate/20250520133235_update_submission_assess_times_to_version_2.rb
db/schema.rb
db/views/submission_assess_times_v02.sql

[Link to relevant ticket](https://dsdmoj.atlassian.net/browse/CRM457-2519)
Filter out records where decision state Submission Version records have null created_at. These are in there because of a datafix that was needed to backfill some records that didn't get created when they should have. At the time there was no way of discerning the created_at value so the updated_at value was only updated with the date of the data fix

CRM457-2519: Create Metrics Report for Time To Assess A Claim pt 2
